#ifndef CONTACTCLIENT_GLOBAL_H
#define CONTACTCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTACTCLIENT_LIBRARY)
#  define CONTACTCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTACTCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTACTCLIENT_GLOBAL_H
